package com.drifai.repositories;

import java.util.UUID;

import org.springframework.data.repository.PagingAndSortingRepository;

import com.drifai.domain.Beer;

/**
 * 
 * @author drifai
 * 
 * Implementation generated by Spring Data
 *
 */
public interface BeerRepository extends PagingAndSortingRepository<Beer, UUID> {

}
